// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBje_sw6k9bDF5yoT4stiWKs86ZzSrtYMI',
    appId: '1:637559040183:web:315eedcaadfe31f42d4532',
    messagingSenderId: '637559040183',
    projectId: 'contentflow-7b3af',
    authDomain: 'contentflow-7b3af.firebaseapp.com',
    storageBucket: 'contentflow-7b3af.firebasestorage.app',
    measurementId: 'G-PT5TMYTDE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACNGD249nxyfHLpnqQS3-Bu1dNNYMgX8Y',
    appId: '1:637559040183:android:6399f8097a72eb292d4532',
    messagingSenderId: '637559040183',
    projectId: 'contentflow-7b3af',
    storageBucket: 'contentflow-7b3af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWL-dQBjqcq2pzzJnXFR63icqCUgiQCY',
    appId: '1:637559040183:ios:7cb3406098e927272d4532',
    messagingSenderId: '637559040183',
    projectId: 'contentflow-7b3af',
    storageBucket: 'contentflow-7b3af.firebasestorage.app',
    iosClientId: '637559040183-qoaa2ih0b5qo8oll2pip0n9pb1ruvjfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.contentflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWL-dQBjqcq2pzzJnXFR63icqCUgiQCY',
    appId: '1:637559040183:ios:7cb3406098e927272d4532',
    messagingSenderId: '637559040183',
    projectId: 'contentflow-7b3af',
    storageBucket: 'contentflow-7b3af.firebasestorage.app',
    iosClientId: '637559040183-qoaa2ih0b5qo8oll2pip0n9pb1ruvjfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.contentflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBje_sw6k9bDF5yoT4stiWKs86ZzSrtYMI',
    appId: '1:637559040183:web:a024dd4d1caf1bc02d4532',
    messagingSenderId: '637559040183',
    projectId: 'contentflow-7b3af',
    authDomain: 'contentflow-7b3af.firebaseapp.com',
    storageBucket: 'contentflow-7b3af.firebasestorage.app',
    measurementId: 'G-LTPBBYCXSV',
  );
}
